In [14]:
import numpy as np
import matplotlib.pyplot as plt

input = np.arange(0, 1024, 1)
max_pwm = 2047

def map_exponential(input, exponent):
    return (np.power((input+1) / 1023, exponent) * max_pwm)

output = map_exponential(input, 2.5).astype(int)

print(input[:10])
print(output[:100])
print(input[-10:])
print(output[-10:])

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 6]
[1014 1015 1016 1017 1018 1019 1020 1021 1022 1023]
[2007 2012 2017 2022 2027 2032 2037 2042 2047 2052]
